// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheStore.Catalog.Infrastructure.Data;

#nullable disable

namespace TheStore.Catalog.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20230414223109_Init_Migration")]
    partial class Init_Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TheStore.Catalog.Core.Aggregates.Branches.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("TheStore.Catalog.Core.Aggregates.Categories.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NeedsSynchronization")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("TheStore.Catalog.Core.Aggregates.Products.SingleProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SingleProducts");

                    b.HasDiscriminator<string>("Discriminator").HasValue("SingleProduct");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TheStore.Catalog.Core.ValueObjects.Keys.ProductId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssembledProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssembledProductId");

                    b.ToTable("ProductId");
                });

            modelBuilder.Entity("TheStore.Catalog.Core.Aggregates.Products.AssembledProduct", b =>
                {
                    b.HasBaseType("TheStore.Catalog.Core.Aggregates.Products.SingleProduct");

                    b.HasDiscriminator().HasValue("AssembledProduct");
                });

            modelBuilder.Entity("TheStore.Catalog.Core.Aggregates.Branches.Branch", b =>
                {
                    b.OwnsOne("TheStore.Catalog.Core.ValueObjects.Image", "Image", b1 =>
                        {
                            b1.Property<int>("BranchId")
                                .HasColumnType("int");

                            b1.Property<string>("Alt")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("StringFileUri")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("BranchId");

                            b1.ToTable("Branches");

                            b1.WithOwner()
                                .HasForeignKey("BranchId");
                        });

                    b.OwnsOne("TheStore.Catalog.Core.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<int>("BranchId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("BranchId");

                            b1.ToTable("Branches");

                            b1.WithOwner()
                                .HasForeignKey("BranchId");

                            b1.OwnsOne("TheStore.Catalog.Core.ValueObjects.Coordinate", "Coordinate", b2 =>
                                {
                                    b2.Property<int>("AddressBranchId")
                                        .HasColumnType("int");

                                    b2.Property<float>("Latitude")
                                        .HasColumnType("real");

                                    b2.Property<float>("Longitude")
                                        .HasColumnType("real");

                                    b2.HasKey("AddressBranchId");

                                    b2.ToTable("Branches");

                                    b2.WithOwner()
                                        .HasForeignKey("AddressBranchId");
                                });

                            b1.Navigation("Coordinate")
                                .IsRequired();
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Image")
                        .IsRequired();
                });

            modelBuilder.Entity("TheStore.Catalog.Core.Aggregates.Products.SingleProduct", b =>
                {
                    b.OwnsOne("TheStore.Catalog.Core.ValueObjects.InventoryRecord", "Inventory", b1 =>
                        {
                            b1.Property<int>("SingleProductId")
                                .HasColumnType("int");

                            b1.Property<int>("AvailableStock")
                                .HasColumnType("int");

                            b1.Property<int>("MaxStockThreshold")
                                .HasColumnType("int");

                            b1.Property<bool>("OnReorder")
                                .HasColumnType("bit");

                            b1.Property<int>("OverStock")
                                .HasColumnType("int");

                            b1.Property<int>("RestockThreshold")
                                .HasColumnType("int");

                            b1.HasKey("SingleProductId");

                            b1.ToTable("SingleProducts");

                            b1.WithOwner()
                                .HasForeignKey("SingleProductId");
                        });

                    b.OwnsOne("TheStore.Catalog.Core.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<int>("SingleProductId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(16, 3)
                                .HasColumnType("decimal(16,3)");

                            b1.HasKey("SingleProductId");

                            b1.ToTable("SingleProducts");

                            b1.WithOwner()
                                .HasForeignKey("SingleProductId");

                            b1.OwnsOne("TheStore.Catalog.Core.ValueObjects.Currency", "Currency", b2 =>
                                {
                                    b2.Property<int>("MoneySingleProductId")
                                        .HasColumnType("int");

                                    b2.Property<string>("CurrencyCode")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("MoneySingleProductId");

                                    b2.ToTable("SingleProducts");

                                    b2.WithOwner()
                                        .HasForeignKey("MoneySingleProductId");
                                });

                            b1.Navigation("Currency")
                                .IsRequired();
                        });

                    b.OwnsMany("TheStore.Catalog.Core.ValueObjects.Products.ProductColor", "productColors", b1 =>
                        {
                            b1.Property<int>("SingleProductId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("ColorCode")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("SingleProductId", "Id");

                            b1.ToTable("ProductColor");

                            b1.WithOwner()
                                .HasForeignKey("SingleProductId");

                            b1.OwnsMany("TheStore.Catalog.Core.ValueObjects.Image", "Images", b2 =>
                                {
                                    b2.Property<int>("ProductColorSingleProductId")
                                        .HasColumnType("int");

                                    b2.Property<int>("ProductColorId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Alt")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("StringFileUri")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("ProductColorSingleProductId", "ProductColorId", "Id");

                                    b2.ToTable("ProductColor_Images");

                                    b2.WithOwner()
                                        .HasForeignKey("ProductColorSingleProductId", "ProductColorId");
                                });

                            b1.Navigation("Images");
                        });

                    b.Navigation("Inventory")
                        .IsRequired();

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("productColors");
                });

            modelBuilder.Entity("TheStore.Catalog.Core.ValueObjects.Keys.ProductId", b =>
                {
                    b.HasOne("TheStore.Catalog.Core.Aggregates.Products.AssembledProduct", null)
                        .WithMany("Parts")
                        .HasForeignKey("AssembledProductId");
                });

            modelBuilder.Entity("TheStore.Catalog.Core.Aggregates.Products.AssembledProduct", b =>
                {
                    b.Navigation("Parts");
                });
#pragma warning restore 612, 618
        }
    }
}
