// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheStore.Catalog.Infrastructure.Data;

#nullable disable

namespace TheStore.Catalog.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20231209021951_NET8_Changes")]
    partial class NET8_Changes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TheStore.Catalog.Core.Aggregates.Branches.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Published")
                        .HasColumnType("bit");

                    b.ComplexProperty<Dictionary<string, object>>("Address", "TheStore.Catalog.Core.Aggregates.Branches.Branch.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.ComplexProperty<Dictionary<string, object>>("Coordinate", "TheStore.Catalog.Core.Aggregates.Branches.Branch.Address#Address.Coordinate#Coordinate", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<float>("Latitude")
                                        .HasColumnType("real");

                                    b2.Property<float>("Longitude")
                                        .HasColumnType("real");
                                });
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Description", "TheStore.Catalog.Core.Aggregates.Branches.Branch.Description#MultilanguageString", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Json")
                                .HasColumnType("nvarchar(max)");
                        });

                    b.HasKey("Id");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("TheStore.Catalog.Core.Aggregates.Categories.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("NeedsSynchronization")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<bool>("Published")
                        .HasColumnType("bit");

                    b.ComplexProperty<Dictionary<string, object>>("Name", "TheStore.Catalog.Core.Aggregates.Categories.Category.Name#MultilanguageString", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Json")
                                .HasColumnType("nvarchar(max)");
                        });

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("TheStore.Catalog.Core.Aggregates.Products.AssembledProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Published")
                        .HasColumnType("bit");

                    b.ComplexProperty<Dictionary<string, object>>("Description", "TheStore.Catalog.Core.Aggregates.Products.AssembledProduct.Description#MultilanguageString", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Json")
                                .HasColumnType("nvarchar(max)");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("ShortDescription", "TheStore.Catalog.Core.Aggregates.Products.AssembledProduct.ShortDescription#MultilanguageString", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Json")
                                .HasColumnType("nvarchar(max)");
                        });

                    b.HasKey("Id");

                    b.ToTable("AssembledProducts");
                });

            modelBuilder.Entity("TheStore.Catalog.Core.Aggregates.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Published")
                        .HasColumnType("bit");

                    b.ComplexProperty<Dictionary<string, object>>("Description", "TheStore.Catalog.Core.Aggregates.Products.Product.Description#MultilanguageString", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Json")
                                .HasColumnType("nvarchar(max)");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("ShortDescription", "TheStore.Catalog.Core.Aggregates.Products.Product.ShortDescription#MultilanguageString", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Json")
                                .HasColumnType("nvarchar(max)");
                        });

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("TheStore.Catalog.Core.Aggregates.Products.ProductVariant", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Key", 0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<bool>("Published")
                        .HasColumnType("bit");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ComplexProperty<Dictionary<string, object>>("Description", "TheStore.Catalog.Core.Aggregates.Products.ProductVariant.Description#MultilanguageString", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Json")
                                .HasColumnType("nvarchar(max)");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("ShortDescription", "TheStore.Catalog.Core.Aggregates.Products.ProductVariant.ShortDescription#MultilanguageString", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Json")
                                .HasColumnType("nvarchar(max)");
                        });

                    b.HasKey("ID");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductVariant");
                });

            modelBuilder.Entity("TheStore.Catalog.Core.Aggregates.Branches.Branch", b =>
                {
                    b.OwnsOne("TheStore.Catalog.Core.ValueObjects.Image", "Image", b1 =>
                        {
                            b1.Property<int>("BranchId")
                                .HasColumnType("int");

                            b1.HasKey("BranchId");

                            b1.ToTable("Branches");

                            b1.WithOwner()
                                .HasForeignKey("BranchId");
                        });

                    b.Navigation("Image");
                });

            modelBuilder.Entity("TheStore.Catalog.Core.Aggregates.Products.ProductVariant", b =>
                {
                    b.HasOne("TheStore.Catalog.Core.Aggregates.Products.Product", null)
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TheStore.Catalog.Core.Aggregates.Products.ProductVariantOptions", "Options", b1 =>
                        {
                            b1.Property<int>("ProductVariantID")
                                .HasColumnType("int");

                            b1.Property<bool>("CanBeFavorited")
                                .HasColumnType("bit");

                            b1.Property<bool>("CanBePurchased")
                                .HasColumnType("bit");

                            b1.HasKey("ProductVariantID");

                            b1.ToTable("ProductVariant");

                            b1.WithOwner()
                                .HasForeignKey("ProductVariantID");
                        });

                    b.OwnsOne("TheStore.Catalog.Core.ValueObjects.Dimentions", "Dimentions", b1 =>
                        {
                            b1.Property<int>("ProductVariantID")
                                .HasColumnType("int");

                            b1.HasKey("ProductVariantID");

                            b1.ToTable("ProductVariant");

                            b1.WithOwner()
                                .HasForeignKey("ProductVariantID");
                        });

                    b.OwnsOne("TheStore.Catalog.Core.ValueObjects.InventoryRecord", "Inventory", b1 =>
                        {
                            b1.Property<int>("ProductVariantID")
                                .HasColumnType("int");

                            b1.Property<int>("AvailableStock")
                                .HasColumnType("int");

                            b1.Property<int>("MaxStockThreshold")
                                .HasColumnType("int");

                            b1.Property<bool>("OnReorder")
                                .HasColumnType("bit");

                            b1.Property<int>("OverStock")
                                .HasColumnType("int");

                            b1.Property<int>("RestockThreshold")
                                .HasColumnType("int");

                            b1.HasKey("ProductVariantID");

                            b1.ToTable("ProductVariant");

                            b1.WithOwner()
                                .HasForeignKey("ProductVariantID");
                        });

                    b.OwnsOne("TheStore.Catalog.Core.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<int>("ProductVariantID")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(8, 2)
                                .HasColumnType("decimal");

                            b1.HasKey("ProductVariantID");

                            b1.ToTable("ProductVariant");

                            b1.WithOwner()
                                .HasForeignKey("ProductVariantID");

                            b1.OwnsOne("TheStore.Catalog.Core.ValueObjects.Currency", "Currency", b2 =>
                                {
                                    b2.Property<int>("MoneyProductVariantID")
                                        .HasColumnType("int");

                                    b2.Property<string>("CurrencyCode")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("MoneyProductVariantID");

                                    b2.ToTable("ProductVariant");

                                    b2.WithOwner()
                                        .HasForeignKey("MoneyProductVariantID");
                                });

                            b1.Navigation("Currency")
                                .IsRequired();
                        });

                    b.OwnsMany("TheStore.Catalog.Core.ValueObjects.ProductReview", "reviews", b1 =>
                        {
                            b1.Property<int>("ProductVariantID")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.HasKey("ProductVariantID", "Id");

                            b1.ToTable("ProductReview");

                            b1.WithOwner()
                                .HasForeignKey("ProductVariantID");
                        });

                    b.OwnsOne("TheStore.Catalog.Core.ValueObjects.ProductSpecifications", "Sepcifications", b1 =>
                        {
                            b1.Property<int>("ProductVariantID")
                                .HasColumnType("int");

                            b1.HasKey("ProductVariantID");

                            b1.ToTable("ProductVariant");

                            b1.WithOwner()
                                .HasForeignKey("ProductVariantID");
                        });

                    b.OwnsOne("TheStore.Catalog.Core.ValueObjects.Products.ProductColor", "Color", b1 =>
                        {
                            b1.Property<int>("ProductVariantID")
                                .HasColumnType("int");

                            b1.HasKey("ProductVariantID");

                            b1.ToTable("ProductVariant");

                            b1.WithOwner()
                                .HasForeignKey("ProductVariantID");

                            b1.OwnsMany("TheStore.Catalog.Core.ValueObjects.Image", "images", b2 =>
                                {
                                    b2.Property<int>("ProductColorProductVariantID")
                                        .HasColumnType("int");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.HasKey("ProductColorProductVariantID", "Id");

                                    b2.ToTable("ProductVariant_images");

                                    b2.WithOwner()
                                        .HasForeignKey("ProductColorProductVariantID");
                                });

                            b1.Navigation("images");
                        });

                    b.Navigation("Color")
                        .IsRequired();

                    b.Navigation("Dimentions")
                        .IsRequired();

                    b.Navigation("Inventory")
                        .IsRequired();

                    b.Navigation("Options")
                        .IsRequired();

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("Sepcifications")
                        .IsRequired();

                    b.Navigation("reviews");
                });

            modelBuilder.Entity("TheStore.Catalog.Core.Aggregates.Products.Product", b =>
                {
                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
