// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheStore.Cart.Infrastructure.Data;

#nullable disable

namespace TheStore.Cart.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CartDbContext))]
    [Migration("20230816125237_Add_Dates_To_Entities")]
    partial class Add_Dates_To_Entities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TheStore.Cart.Core.Aggregates.Buyer", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Buyers");
                });

            modelBuilder.Entity("TheStore.Cart.Core.Aggregates.Cart", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("BuyerIdId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateUpdated")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("BuyerIdId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("TheStore.Cart.Core.Aggregates.Wishlist", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("BuyerIdId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateUpdated")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("BuyerIdId");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("TheStore.Cart.Core.ValueObjects.Keys.BuyerId", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("BuyerId");
                });

            modelBuilder.Entity("TheStore.Cart.Core.Aggregates.Cart", b =>
                {
                    b.HasOne("TheStore.Cart.Core.ValueObjects.Keys.BuyerId", "BuyerId")
                        .WithMany()
                        .HasForeignKey("BuyerIdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("TheStore.Cart.Core.Entities.CartItem", "items", b1 =>
                        {
                            b1.Property<string>("CartId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("ProductId")
                                .HasColumnType("int");

                            b1.Property<int>("Quantity")
                                .HasColumnType("int");

                            b1.HasKey("CartId", "Id");

                            b1.ToTable("CartItem");

                            b1.WithOwner()
                                .HasForeignKey("CartId");
                        });

                    b.Navigation("BuyerId");

                    b.Navigation("items");
                });

            modelBuilder.Entity("TheStore.Cart.Core.Aggregates.Wishlist", b =>
                {
                    b.HasOne("TheStore.Cart.Core.ValueObjects.Keys.BuyerId", "BuyerId")
                        .WithMany()
                        .HasForeignKey("BuyerIdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("TheStore.Cart.Core.Entities.WishlistItem", "items", b1 =>
                        {
                            b1.Property<string>("WishlistId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("ProductId")
                                .HasColumnType("int");

                            b1.HasKey("WishlistId", "Id");

                            b1.ToTable("WishlistItem");

                            b1.WithOwner()
                                .HasForeignKey("WishlistId");
                        });

                    b.Navigation("BuyerId");

                    b.Navigation("items");
                });
#pragma warning restore 612, 618
        }
    }
}
