version: '3.4'

services:
  thestore.catalog.api:
    image: ${DOCKER_REGISTRY-}thestorecatalogapi
    build:
      context: .
      dockerfile: APIs/Catalog/TheStore.Catalog.API/Dockerfile

  thestore.auth:
    image: ${DOCKER_REGISTRY-}thestoreauth
    build:
      context: .
      dockerfile: Identity/TheStore.Auth/Dockerfile


  thestore.web:
    image: ${DOCKER_REGISTRY-}thestoreweb
    build:
      context: .
      dockerfile: Web/TheStore.Web/Dockerfile

